apiVersion: v1
kind: Service
metadata:
  name: remotedictionary-service
spec:
  selector:
    app: remotedictionary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7171
  type: LoadBalancer
